"""add composite indexes

Revision ID: 465bb1f67725
Revises: 4a9118c028f9
Create Date: 2026-09-06 14:14:03.872349
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '465bb1f67725'
down_revision: str | None = '4a9118c028f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_integrations', schema=None) as batch_op:
        batch_op.create_index('ix_github_integrations_repo', ['repo_owner', 'repo_name'], unique=False)

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index('ix_time_entries_user_start', ['user_id', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_time_entries_user_start')

    with op.batch_alter_table('github_integrations', schema=None) as batch_op:
        batch_op.drop_index('ix_github_integrations_repo')

    # ### end Alembic commands ###
