"""initial schema

Revision ID: 4a9118c028f9
Revises: 
Create Date: 2026-09-06 13:55:04.346757
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4a9118c028f9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('webhook_event_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('processed_successfully', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('ORG_OWNER', 'ORG_ADMIN', 'PROJECT_MANAGER', 'MEMBER', 'GUEST', name='orgrole', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_member')
    )
    with op.batch_alter_table('org_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_members_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_members_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'slug', name='uq_workspace_org_slug')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_org_id'), ['org_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_view', sa.String(length=50), nullable=False),
    sa.Column('task_counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_project_org_key')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('github_integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repo_owner', sa.String(length=100), nullable=False),
    sa.Column('repo_name', sa.String(length=100), nullable=False),
    sa.Column('auto_transition_pr_open', sa.Boolean(), nullable=False),
    sa.Column('auto_transition_pr_merge', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_integrations_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_integrations_project_id'), ['project_id'], unique=False)

    op.create_table('sprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprints_project_id'), ['project_id'], unique=False)

    op.create_table('workflow_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', name='statuscategory', native_enum=False, length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_statuses_project_id'), ['project_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sprint_id', sa.String(length=36), nullable=True),
    sa.Column('status_id', sa.String(length=36), nullable=False),
    sa.Column('short_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', name='taskpriority', native_enum=False, length=20), nullable=False),
    sa.Column('story_points', sa.Float(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['workflow_statuses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'short_id', name='uq_task_project_short_id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_short_id'), ['short_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_sprint_id'), ['sprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status_id'), ['status_id'], unique=False)

    op.create_table('figma_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('figma_url', sa.String(length=512), nullable=False),
    sa.Column('file_key', sa.String(length=100), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('figma_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_figma_links_task_id'), ['task_id'], unique=False)

    op.create_table('subtasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtasks_task_id'), ['task_id'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('predecessor_id', sa.String(length=36), nullable=False),
    sa.Column('successor_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_type', sa.Enum('BLOCKS', 'BLOCKED_BY', 'RELATES_TO', name='dependencytype', native_enum=False, length=20), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', name='uq_task_dependency_pair')
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_predecessor_id'), ['predecessor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_successor_id'), ['successor_id'], unique=False)

    op.create_table('time_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_seconds', sa.Integer(), nullable=False),
    sa.Column('idle_seconds', sa.Integer(), nullable=False),
    sa.Column('activity_percent', sa.Float(), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='timeentrystatus', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entries_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_user_id'), ['user_id'], unique=False)

    op.create_table('activity_telemetries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('time_entry_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keystroke_count', sa.Integer(), nullable=False),
    sa.Column('mouse_distance_px', sa.Integer(), nullable=False),
    sa.Column('active_window_title', sa.String(length=255), nullable=True),
    sa.Column('is_idle', sa.Boolean(), nullable=False),
    sa.Column('activity_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_telemetries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_telemetries_time_entry_id'), ['time_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_telemetries_user_id'), ['user_id'], unique=False)

    op.create_table('screenshot_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('time_entry_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_s3_key', sa.String(length=512), nullable=True),
    sa.Column('activity_score', sa.Float(), nullable=False),
    sa.Column('is_blurred', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenshot_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenshot_logs_time_entry_id'), ['time_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenshot_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenshot_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenshot_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_screenshot_logs_time_entry_id'))

    op.drop_table('screenshot_logs')
    with op.batch_alter_table('activity_telemetries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_telemetries_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_telemetries_time_entry_id'))

    op.drop_table('activity_telemetries')
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_task_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_org_id'))

    op.drop_table('time_entries')
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_successor_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_predecessor_id'))

    op.drop_table('task_dependencies')
    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtasks_task_id'))

    op.drop_table('subtasks')
    with op.batch_alter_table('figma_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_figma_links_task_id'))

    op.drop_table('figma_links')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_sprint_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_short_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_org_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_creator_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('workflow_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_statuses_project_id'))

    op.drop_table('workflow_statuses')
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprints_project_id'))

    op.drop_table('sprints')
    with op.batch_alter_table('github_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_integrations_project_id'))
        batch_op.drop_index(batch_op.f('ix_github_integrations_org_id'))

    op.drop_table('github_integrations')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_projects_org_id'))
        batch_op.drop_index(batch_op.f('ix_projects_key'))

    op.drop_table('projects')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_org_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('org_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_org_members_org_id'))

    op.drop_table('org_members')
    op.drop_table('webhook_event_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
