"""add webhook log index

Revision ID: bf0d42eb4aa8
Revises: 465bb1f67725
Create Date: 2026-09-06 15:06:00.786102
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf0d42eb4aa8'
down_revision: str | None = '465bb1f67725'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_event_logs', schema=None) as batch_op:
        batch_op.create_index('ix_webhook_event_logs_provider_created', ['provider', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_event_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_webhook_event_logs_provider_created')

    # ### end Alembic commands ###
